subclass_name: ColorRedshiftTest.ColorRedshiftTest
observation: ''
description: 'Trying to get this test to run on the data'
# - frame: obs
#   color: r-i
#   filter: lsst
#   # central: true
#   # Mr_cut: -20
#   # mr_cut: 20
#   # stellar_mass_cut: 9.5
#   halo_mass_cut: 13
#   red_sequence_cut: true
#   log_scale: true

frame: obs
color: r-i
filter: sdss
central: true
Mr_cut: -20
mr_cut: 20
stellar_mass_cut: 9.5
halo_mass_cut: 13
red_sequence_cut: true
log_scale: true

plot_list:

- frame: obs
  color: g-r
  filter: lsst
  log_scale: true

- frame: obs
  color: r-i
  filter: lsst
  log_scale: true

- frame: obs
  color: i-z
  filter: lsst
  log_scale: true

- frame: obs
  color: r-i
  filter: lsst
  central: true
  Mr_cut: -20
  mr_cut: 20 
  stellar_mass_cut: 9.5
  halo_mass_cut: 13
  red_sequence_cut: true
  log_scale: true