subclass_name: ColorDistribution.ColorDistribution
obs_r_mag_limit: 24.0
zlo: 0.85
zhi: 0.95
validation_catalog: DEEP2
plot_pdf_q: true
plot_cdf_q: false
color_transformation_q: true
truncate_cat_name: true
plot_shift: true
title_in_legend: true
legend_location: best
font_size: 18
legend_size: 12

description: Compare the mock galaxy color distribution with DEEP2