subclass_name: EmlineRatioTest.EmlineRatioTest
emline_ratio1: 'oii/oiii'
emline_ratio2: 'hb/oiii'
sdss_file: 'sdss_emission_lines/sdss_query_snr10_ew.csv'
sdss_drawnum: 30000
sim_drawnum: 30000
description: 'Plots ratios of emission line luminosities from SDSS data and DESC simulations and compares the two 2-D distributions.'