subclass_name: ImgPkTest.ImgPkTest
description: 'Compute power spectrum of the background' 
included_by_default: true

input_path: '/global/homes/j/jsanch87/quick_pk_bkg/Pk_9.fits.gz'
val_label: 'Test 9'
raft: 'R22'
