subclass_name: CorrelationsTwoPoint.CorrelationsTwoPoint

output_filename_template: 'wp_rp_{}.dat'
label_template: '${} < M_r < {}$'

data_filename: 'tpcf/Zehavi_2011_ApJ_736_59_Table7.txt'
data_label: 'Zehavi+2011'

requested_columns:
  ra:
    - ra
    - ra_true
  dec:
    - dec
    - dec_true
  mag:
    - Mag_true_r_sdss_z0
    - Mag_true_r_des_z0
    - Mag_true_r_lsst_z0
    - Mag_true_r_sdss_z01
    - Mag_true_r_des_z01
    - Mag_true_r_lsst_z01
  z:
    - redshift
    - redshift_true

test_samples:
  Mr_-23_-22:
    mag: {min: -23, max: -22}
    redshift: {min: 0.1031, max: 0.2452}
  Mr_-22_-21:
    mag: {min: -22, max: -21}
    redshift: {min: 0.0663, max: 0.1589}
  Mr_-21_-20:
    mag: {min: -21, max: -20}
    redshift: {min: 0.0420, max: 0.1064}
  Mr_-20_-19:
    mag: {min: -20, max: -19}
    redshift: {min: 0.0269, max: 0.0642}

data_filename: 'tpcf/Zehavi_2011_ApJ_736_59_Table7.txt'
data_label: 'Zehavi+2011'
test_data:
  - {data_col: 1, data_err_col: 2}
  - {data_col: 3, data_err_col: 4}
  - {data_col: 5, data_err_col: 6}
  - {data_col: 7, data_err_col: 8}

need_distance: true
fig_xlabel: '$r_p\quad[h^{-1}{\rm Mpc}]$'
fig_ylabel: '$w_p(r_p)\quad[h^{-1}{\rm Mpc}]$'
fig_ylim: [0.1, 5000]

#Treecorr parameters
min_sep: 0.15
max_sep: 40
bin_size: 0.45
pi_max: 60.0

random_mult: 6

description: |
  Compare projected correlation functions of catalog and Zehavi et al (2011) SDSS r-band observations

included_by_default: true